spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: Order_Service
          uri: http://localhost:8012
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: Order_Service
                fallbackuri: forward:/orderFallBack
        - id: User_Service
          uri: http://localhost:8021
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: User_Service
                fallbackuri: forward:/userFallBack
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream



#zuul:
#routes:
#  products:
#    path: /orders/**, /user/**
#    url: http://localhost:8012/, http://localhost:8021/

server:
  port: 8022

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
